FROM node:18-alpine
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build --workspace=@sanjeevani/shared-types
RUN npm run prisma:generate --workspace=@sanjeevani/api
RUN npm run build --workspace=@sanjeevani/api
ENV NODE_ENV=production
ENV PORT=3000
EXPOSE 3000
CMD ["npm", "run", "start:prod", "--workspace=@sanjeevani/api"]

